__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/optimizer.yml',
  '../base/deimv2.yml',
]

output_dir: ./outputs/deimv2_dinov3_s_fisheye_batch2_832_amp_200e

num_classes: 5
remap_mscoco_category: False
eval_spatial_size: [1024, 1024]

DEIM:
  backbone: DINOv3STAs

DINOv3STAs:
  name: vit_tiny
  embed_dim: 192
  weights_path: ./ckpts/vitt_distill.pt
  interaction_indexes: [3, 7, 11]
  num_heads: 3

HybridEncoder:
  in_channels: [192, 192, 192]
  depth_mult: 0.67
  expansion: 0.34
  hidden_dim: 192
  dim_feedforward: 512

DEIMTransformer:
  feat_channels: [192, 192, 192]
  hidden_dim: 192
  dim_feedforward: 512
  num_layers: 4
  eval_idx: -1

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*dinov3)(?!.*(?:norm|bn|bias)).*$'
      lr: 0.000010
    -
      params: '^(?=.*dinov3)(?=.*(?:norm|bn|bias)).*$'
      lr: 0.000010
      weight_decay: 0.
    -
      params: '^(?=.*(?:sta|encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.0001

epoches: 200
flat_epoch: 100
no_aug_epoch: 20

train_dataloader:
  total_batch_size: 2
  dataset:
    img_folder: /path/to/project/deimv2_data/train/images
    ann_file: /path/to/project/deimv2_data/annotations/train.json
    transforms:
      ops:
        - {type: Mosaic, output_size: 416, rotation_range: 6, translation_range: [0.06, 0.06], scaling_range: [0.8, 1.2], probability: 0.20, fill_value: 0, use_cache: True, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.25}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [1024, 1024]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        epoch: [8, 100, 180]

  collate_fn:
    base_size: 832
    mixup_prob: 0.0
    ema_restart_decay: 0.9999
    base_size_repeat: 10
    mixup_epochs: [8, 100]
    stop_epoch: 180
    copyblend_epochs: [0, 0]

val_dataloader:
  total_batch_size: 2
  dataset:
    img_folder: /path/to/project/deimv2_data/val/images
    ann_file: /path/to/project/deimv2_data/annotations/val.json
    transforms:
      ops:
        - {type: Resize, size: [1024, 1024]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}

DEIMCriterion:
  matcher:
    change_matcher: True
    iou_order_alpha: 4.0
    matcher_change_epoch: 162